workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

stages:
  - build
  - test

build-app:
  stage: build
  image: python:3.12
  script:
    - echo "Start building app"
    - pip install -r requirements.txt
    - echo "Build step complete"

unittest:
  stage: test
  script:
    - echo "Running pytest"
    - pytest tests
    - echo "Tests completed"

mypy:
  stage: test
  script:
    - mypy app/

black:
  stage: test
  script:
    - black --check --diff app/

isort:
  stage: test
  script:
    - isort --check-only --diff app/

flake8:
  stage: test
  script:
    - flake8 app/